# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

glm_wls_c <- function(y, X, pBigMat, weights, threads = 0L) {
    .Call(`_RcppTest_glm_wls_c`, y, X, pBigMat, weights, threads)
}

arma_test <- function() {
    invisible(.Call(`_RcppTest_arma_test`))
}

